/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/* Este archivo .c es el STUB que forma parte del mildware en la comunicacion distribuida
ubicado en el lado del cliente, adicional a esto, las primeras variables se entienden con relacion a su funcion, y al momento de llamar a la funcioon clnt_call es cuando viene en parte la complicacion ya que son necesarias para la serealizacion y creacion del resultado que se enviara al skeleton, pero,
por parte del equipo estas no las comprendimos

*/

#include <memory.h> /* for memset */ //llamada a librerias
#include "sumar.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };//Tiempo de espera antes de abortar operacion

int *
suma_1(dupla_int *argp, CLIENT *clnt)//Cliente y estructura que guarda los 2 numeros a sumar
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));//Serealizacion y llamada al RPC
	if (clnt_call (clnt, SUMA,
		(xdrproc_t) xdr_dupla_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
