/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/* Este archivo ayuda a mantener heterogeneidad entre diferentes lenguajes de programacion
haciendo a los valores de las variables tener un formato estandar.

*/
#include "sumar.h"

bool_t
xdr_dupla_int (XDR *xdrs, dupla_int *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
