/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

/* Este en nuestra opinion es el archivo .c mas complejo y con las variables mas dificiles de entender
a diferencia de los otros codigos para el cliente y el servidor. Cabe aclarar tambien que este es el codigo que forma la otra parte del mildware para la comunicacion distribuida siendo este el skeleton ubicado del lado servidor

*/

#include "sumar.h" //LLamada a librerias
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
suma_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dupla_int suma_1_arg;
	} argument;
	char *result; //Declaracion de una variable para enviar la respuesta a la llamada del servicio
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) { //Declaracion un switch para la llamada 
	//a cualquier funcion que ofrezca el servidor
	case NULLPROC: //caso nulo
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA: //servicio/funcion SUMA
		_xdr_argument = (xdrproc_t) xdr_dupla_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) suma_1_svc;
		break;

	default:
		svcerr_noproc (transp); //Error de sistema
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);//Error de sistema
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);//Si gurge un error se imprime en un archivo y sale del codigo
	}
	return;
}

int
main (int argc, char **argv) //Funcion main del SKELETON
{
	register SVCXPRT *transp; //Se registra el servicio

	pmap_unset (SUMA_PROG, SUMA_VERS);

	transp = svcudp_create(RPC_ANYSOCK);//Uso del servicio UDP
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);//Si gurge un error se imprime en un archivo y sale del codigo
	}
	if (!svc_register(transp, SUMA_PROG, SUMA_VERS, suma_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUMA_PROG, SUMA_VERS, udp).");
		exit(1);//Si gurge un error se imprime en un archivo y sale del codigo
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);//Uso del servicio TCP
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);//Si gurge un error se imprime en un archivo y sale del codigo
	}
	if (!svc_register(transp, SUMA_PROG, SUMA_VERS, suma_prog_1, IPPROTO_TCP)) {
	//Comprobacion que se registro el servicio TCP
		fprintf (stderr, "%s", "unable to register (SUMA_PROG, SUMA_VERS, tcp).");
		exit(1);//Si gurge un error se imprime en un archivo y sale del codigo
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");//Error al arrancar
	exit (1);
	/* NOTREACHED */
}
